### ISSUE TITLE
Add the following styling for Mailchimp sign ups

### ISSUE THREAD

**Issue by idmontie** [CapsuleCat/CapsuleCatWordPressTheme#6]
``` css
#mc_embed_signup {
    border: 1px solid #aaa;
    background-color: #eee;
    margin: 50px auto;
    width: 700px;
}
```
