### ISSUE TITLE
Change shadow around images

### ISSUE THREAD

**Issue by idmontie** [CapsuleCat/CapsuleCatWordPressTheme#8]
``` css
.page__main img {
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.8);
}
```
